name:                groebner
version:             0.1.0.0
github:              "neclitoris/groebner"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/groebner#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12 && < 1
- prettyprinter >= 1.7 && < 2
- text >= 1.2 && < 2
- transformers >= 0.5 && < 1
- template-haskell >= 2.16 && < 3
when:
  - condition: impl(ghc >= 9.0)
    then:
      dependencies:
        - singletons >= 3.0 && < 3.1
        - singletons-base >= 3.0 && < 3.1
    else:
      dependencies:
        - singletons >= 2.7 && < 3

library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-patterns

tests:
  groebner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - groebner
    - tasty >= 1.4 && < 2
    - tasty-hedgehog >= 1 && < 2
    - hedgehog >= 1 && < 2
    - tasty-hunit >= 0.10 && < 1
    - HUnit >= 1.6 && < 2

benchmarks:
  groebner-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -rtsopts
    dependencies:
    - groebner
    - criterion >= 1.5 && < 2

default-extensions:
- ImportQualifiedPost
- BlockArguments
- ViewPatterns
